default: &default
  adapter: postgresql
  encoding: unicode
  username: tj
  password: shinjite
  host: localhost
  pool: 5

development:
  <<: *default
  database: StackOverflowClone_development

test:
  <<: *default
  database: StackOverflowClone_test

# production:
#   <<: *default
#   database: StackOverflowClone_production
#   username: StackOverflowClone
#   password: <%= ENV['STACKOVERFLOWCLONE_DATABASE_PASSWORD'] %>
