# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ecb43f7c3aa5883430e17f7616473812758c8b71a9c1002dc2a49174fc1dab696c86799f1404310055220867728c894fb5962c6ed4d6e2f53f5e8d70c3ba58

test:
  secret_key_base: c2e55f7c2cb67adc06c0ae1c400f7a26abb6adcee9c1bd51b24ce11029a057cb54fddd04dfa2f24d1f1152b3c69c4eb85f3fcc66491f38e15dbc595797a0290b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
